"""Body-system disease contracts for eICU factual routers.

These contracts extend Chapter B beyond single diseases into broad organ-system
coverage.  Each module is still disease-specific at runtime: it has its own
cohort definition, target/action contract, active-window rule, and held-out
router gate.  Nothing here grants shared latent-space, causal, clinical, or
runtime action authority.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field

from eicu_aki_transition_extract import (
    DIURETIC_TERMS,
    NEPHROTOXIN_TERMS,
    RENAL_REPLACEMENT_TERMS,
)
from eicu_respiratory_transition_extract import (
    BRONCHODILATOR_TERMS,
    SYSTEMIC_STEROID_TERMS,
)
from eicu_sepsis_transition_extract import (
    ANTIBIOTIC_TERMS,
    FLUID_TERMS,
    VASOPRESSOR_TERMS,
    VENTILATION_TERMS,
)


INOTROPE_TERMS = (
    "dobutamine",
    "milrinone",
    "inamrinone",
    "isoproterenol",
)

ANTIARRHYTHMIC_TERMS = (
    "amiodarone",
    "lidocaine",
    "procainamide",
    "diltiazem",
    "verapamil",
    "metoprolol",
    "esmolol",
)

ANTICOAGULANT_TERMS = (
    "heparin",
    "enoxaparin",
    "lovenox",
    "warfarin",
    "argatroban",
    "bivalirudin",
)

ANTIPLATELET_TERMS = (
    "aspirin",
    "clopidogrel",
    "plavix",
    "ticagrelor",
    "prasugrel",
)

ANTIEPILEPTIC_TERMS = (
    "levetiracetam",
    "keppra",
    "phenytoin",
    "fosphenytoin",
    "valproate",
    "valproic",
    "lacosamide",
    "lorazepam",
    "midazolam",
)

OSMOTHERAPY_TERMS = (
    "mannitol",
    "hypertonic saline",
    "3% saline",
    "sodium chloride 3",
    "23.4% sodium chloride",
)

HEPATIC_ENCEPHALOPATHY_TERMS = (
    "lactulose",
    "rifaximin",
)

TRANSFUSION_TERMS = (
    "packed red blood",
    "packed red blood cells",
    "prbc",
    "prbcs",
    "rbc transfusion",
    "red blood cell",
    "red blood cells",
    "platelet transfusion",
    "platelet concentrate",
    "fresh frozen plasma",
    "ffp",
    "cryoprecipitate",
    "blood product",
    "blood products",
    "transfusion",
    "transfuse",
)

INSULIN_TERMS = (
    "insulin",
    "regular insulin",
    "humalog",
    "lispro",
    "novolog",
    "aspart",
    "lantus",
    "glargine",
    "nph",
)

DEXTROSE_TERMS = (
    "dextrose",
    "d50",
    "d10",
    "d5w",
    "glucose",
)

CALCIUM_REPLETION_TERMS = (
    "calcium chloride",
    "calcium gluconate",
    "calcium",
)

MAGNESIUM_REPLETION_TERMS = (
    "magnesium sulfate",
    "magnesium",
)

PHOSPHATE_REPLETION_TERMS = (
    "potassium phosphate",
    "sodium phosphate",
    "phosphate",
    "phos",
)

POTASSIUM_REPLETION_TERMS = (
    "potassium chloride",
    "kcl",
    "potassium",
)

BICARBONATE_TERMS = (
    "sodium bicarbonate",
    "bicarbonate",
    "bicarb",
)

NUTRITION_TERMS = (
    "tpn",
    "total parenteral nutrition",
    "parenteral nutrition",
    "enteral",
    "tube feed",
    "tube feeding",
    "nutrition",
    "lipid",
    "lipids",
)

PPI_TERMS = (
    "pantoprazole",
    "protonix",
    "omeprazole",
    "prilosec",
    "lansoprazole",
    "esomeprazole",
)

OCTREOTIDE_TERMS = (
    "octreotide",
    "sandostatin",
)

ALBUMIN_TERMS = (
    "albumin",
)

WOUND_CARE_TERMS = (
    "wound care",
    "wound dressing",
    "dressing change",
    "debridement",
    "wound vac",
    "negative pressure",
    "pressure ulcer",
    "decubitus",
    "skin graft",
)

TOPICAL_ANTIMICROBIAL_TERMS = (
    "silver sulfadiazine",
    "silvadene",
    "mafenide",
    "collagenase",
    "santyl",
    "bacitracin",
    "mupirocin",
)

ANTIDOTE_TERMS = (
    "naloxone",
    "narcan",
    "acetylcysteine",
    "n-acetylcysteine",
    "n acetylcysteine",
    "mucomyst",
    "fomepizole",
    "flumazenil",
    "glucagon",
    "hydroxocobalamin",
    "cyanokit",
    "atropine",
    "pralidoxime",
)

DECONTAMINATION_TERMS = (
    "activated charcoal",
    "charcoal",
    "whole bowel irrigation",
    "gastric lavage",
)

TOXIC_SUPPORT_TERMS = (
    "thiamine",
    "pyridoxine",
    "folinic acid",
    "leucovorin",
    "lipid emulsion",
    "intralipid",
)


@dataclass(frozen=True)
class BodySystemDiseaseConfig:
    name: str
    display_name: str
    body_system: str
    diagnosis_patterns: tuple[str, ...]
    targets: tuple[str, ...]
    state_vars: tuple[str, ...]
    action_terms: dict[str, tuple[str, ...]]
    active_low: dict[str, float] = field(default_factory=dict)
    active_high: dict[str, float] = field(default_factory=dict)
    active_actions: tuple[str, ...] = field(default_factory=tuple)
    notes: tuple[str, ...] = field(default_factory=tuple)

    @property
    def action_keys(self) -> tuple[str, ...]:
        return tuple(self.action_terms.keys())

    def as_report_dict(self) -> dict[str, object]:
        return asdict(self) | {"action_keys": self.action_keys}


BODY_SYSTEM_CONFIGS: dict[str, BodySystemDiseaseConfig] = {
    "integumentary_skin_wound": BodySystemDiseaseConfig(
        name="integumentary_skin_wound",
        display_name="Integumentary / skin / wound / burn proxy",
        body_system="integumentary",
        diagnosis_patterns=(
            "pressure ulcer",
            "decubitus",
            "wound",
            "cellulitis",
            "abscess",
            "skin infection",
            "burn",
            "fasciitis",
            "necrotizing",
            "gangrene",
            "ulcer",
            "dermatitis",
            "l89",
            "l03",
            "l02",
            "l97",
            "t20",
            "t21",
            "t22",
            "t23",
            "t24",
            "t25",
            "t30",
            "707",
            "682",
            "686",
            "728.86",
            "940",
            "941",
            "942",
            "943",
            "944",
            "945",
            "946",
            "948",
            "949",
        ),
        targets=(
            "temperature",
            "wbc",
            "lactate",
            "map",
            "heart_rate",
            "hemoglobin",
            "hematocrit",
            "albumin",
            "glucose",
            "creatinine",
            "platelets",
        ),
        state_vars=(
            "temperature",
            "wbc",
            "lactate",
            "map",
            "heart_rate",
            "hemoglobin",
            "hematocrit",
            "albumin",
            "glucose",
            "creatinine",
            "bun",
            "platelets",
            "bicarbonate",
            "ph",
            "sodium",
            "potassium",
            "o2sat",
            "respiratory_rate",
        ),
        action_terms={
            "wound_care": WOUND_CARE_TERMS,
            "topical_antimicrobial": TOPICAL_ANTIMICROBIAL_TERMS,
            "antibiotics": ANTIBIOTIC_TERMS,
            "fluids": FLUID_TERMS,
            "vasopressor": VASOPRESSOR_TERMS,
            "transfusion": TRANSFUSION_TERMS,
            "nutrition": NUTRITION_TERMS,
        },
        active_low={"albumin": 2.5, "hemoglobin": 8.0, "map": 65.0, "platelets": 100.0},
        active_high={"temperature": 38.5, "wbc": 12.0, "lactate": 2.0, "glucose": 250.0, "creatinine": 2.0, "heart_rate": 120.0},
        active_actions=("hist_wound_care", "hist_topical_antimicrobial", "hist_antibiotics"),
        notes=(
            "Integumentary coverage is a bounded physiology proxy; eICU skin/wound details are mostly text.",
            "No wound-healing, burn-resuscitation, debridement, or topical-treatment effect claim is allowed.",
        ),
    ),
    "toxic_metabolic": BodySystemDiseaseConfig(
        name="toxic_metabolic",
        display_name="Toxicologic / metabolic poisoning proxy",
        body_system="toxicologic_metabolic",
        diagnosis_patterns=(
            "overdose",
            "poison",
            "poisoning",
            "toxicity",
            "toxic",
            "ingestion",
            "intoxication",
            "acetaminophen",
            "salicylate",
            "ethylene glycol",
            "methanol",
            "carbon monoxide",
            "alcohol intoxication",
            "drug abuse",
            "substance abuse",
            "t36",
            "t37",
            "t38",
            "t39",
            "t40",
            "t41",
            "t42",
            "t43",
            "t44",
            "t45",
            "t46",
            "t47",
            "t48",
            "t49",
            "t50",
            "t51",
            "t52",
            "t53",
            "t54",
            "t55",
            "t56",
            "t57",
            "t58",
            "t59",
            "t60",
            "t61",
            "t62",
            "t63",
            "t64",
            "t65",
            "965",
            "966",
            "967",
            "968",
            "969",
            "970",
            "971",
            "977",
            "980",
            "982",
            "983",
            "984",
            "985",
            "986",
            "987",
            "989",
        ),
        targets=(
            "anion_gap",
            "bicarbonate",
            "ph",
            "lactate",
            "serum_osmolality",
            "glucose",
            "potassium",
            "calcium",
            "map",
            "heart_rate",
            "respiratory_rate",
            "o2sat",
            "creatinine",
            "temperature",
        ),
        state_vars=(
            "anion_gap",
            "bicarbonate",
            "ph",
            "lactate",
            "serum_osmolality",
            "glucose",
            "potassium",
            "sodium",
            "chloride",
            "calcium",
            "magnesium",
            "phosphate",
            "map",
            "heart_rate",
            "respiratory_rate",
            "o2sat",
            "creatinine",
            "bun",
            "temperature",
        ),
        action_terms={
            "antidote": ANTIDOTE_TERMS,
            "decontamination": DECONTAMINATION_TERMS,
            "toxic_support": TOXIC_SUPPORT_TERMS,
            "bicarbonate": BICARBONATE_TERMS,
            "renal_replacement": RENAL_REPLACEMENT_TERMS,
            "ventilation": VENTILATION_TERMS,
            "fluids": FLUID_TERMS,
            "vasopressor": VASOPRESSOR_TERMS,
        },
        active_low={"bicarbonate": 18.0, "ph": 7.30, "glucose": 70.0, "map": 65.0, "o2sat": 92.0, "respiratory_rate": 8.0, "temperature": 35.0},
        active_high={"anion_gap": 16.0, "lactate": 2.0, "serum_osmolality": 310.0, "glucose": 250.0, "potassium": 5.5, "temperature": 39.0, "heart_rate": 120.0, "creatinine": 2.0},
        active_actions=("hist_antidote", "hist_decontamination", "hist_bicarbonate", "hist_renal_replacement"),
        notes=(
            "Toxicologic coverage is a physiologic proxy; eICU lacks reliable toxin-level trajectories.",
            "No antidote, dialysis, decontamination, or overdose-treatment effect claim is allowed.",
        ),
    ),
    "electrolyte_acid_base": BodySystemDiseaseConfig(
        name="electrolyte_acid_base",
        display_name="Electrolyte / acid-base / osmotic instability",
        body_system="fluid_electrolyte_acid_base",
        diagnosis_patterns=(
            "hyponatremia",
            "hypernatremia",
            "hypokalemia",
            "hyperkalemia",
            "hypomagnesemia",
            "hypermagnesemia",
            "hypophosphatemia",
            "hyperphosphatemia",
            "hypocalcemia",
            "hypercalcemia",
            "metabolic acidosis",
            "metabolic alkalosis",
            "electrolyte",
            "dehydration",
            "fluid overload",
            "276",
            "e87",
        ),
        targets=(
            "sodium",
            "potassium",
            "chloride",
            "bicarbonate",
            "anion_gap",
            "calcium",
            "ionized_calcium",
            "magnesium",
            "phosphate",
            "serum_osmolality",
            "map",
            "creatinine",
        ),
        state_vars=(
            "sodium",
            "potassium",
            "chloride",
            "bicarbonate",
            "anion_gap",
            "calcium",
            "ionized_calcium",
            "magnesium",
            "phosphate",
            "serum_osmolality",
            "ph",
            "creatinine",
            "bun",
            "glucose",
            "map",
            "heart_rate",
            "urine_output",
        ),
        action_terms={
            "fluids": FLUID_TERMS,
            "diuretics": DIURETIC_TERMS,
            "renal_replacement": RENAL_REPLACEMENT_TERMS,
            "potassium_repletion": POTASSIUM_REPLETION_TERMS,
            "magnesium_repletion": MAGNESIUM_REPLETION_TERMS,
            "phosphate_repletion": PHOSPHATE_REPLETION_TERMS,
            "calcium_repletion": CALCIUM_REPLETION_TERMS,
            "bicarbonate": BICARBONATE_TERMS,
            "insulin": INSULIN_TERMS,
            "dextrose": DEXTROSE_TERMS,
        },
        active_low={"sodium": 130.0, "potassium": 3.2, "bicarbonate": 18.0, "calcium": 7.5, "magnesium": 1.5, "phosphate": 2.0, "map": 65.0},
        active_high={"sodium": 150.0, "potassium": 5.5, "anion_gap": 16.0, "chloride": 112.0, "serum_osmolality": 310.0, "creatinine": 2.0},
        active_actions=("hist_fluids", "hist_diuretics", "hist_renal_replacement"),
        notes=(
            "First-class electrolyte/acid-base factual router; not an electrolyte-repletion causal model.",
            "Treatment channels are observed evidence only.",
        ),
    ),
    "endocrine_stress": BodySystemDiseaseConfig(
        name="endocrine_stress",
        display_name="Endocrine / glycemic / adrenal-thyroid stress",
        body_system="endocrine_metabolic",
        diagnosis_patterns=(
            "diabetes",
            "hyperglycemia",
            "hypoglycemia",
            "hyperosmolar",
            "hhs",
            "adrenal",
            "adrenal insufficiency",
            "adrenal crisis",
            "thyroid storm",
            "thyrotoxicosis",
            "myxedema",
            "hypothyroid",
            "e11",
            "e10",
            "e27",
            "e05",
            "e03",
        ),
        targets=(
            "glucose",
            "serum_osmolality",
            "serum_ketones",
            "anion_gap",
            "bicarbonate",
            "sodium",
            "potassium",
            "tsh",
            "free_t4",
            "cortisol",
            "map",
            "temperature",
        ),
        state_vars=(
            "glucose",
            "serum_osmolality",
            "serum_ketones",
            "anion_gap",
            "bicarbonate",
            "ph",
            "sodium",
            "potassium",
            "tsh",
            "free_t4",
            "cortisol",
            "map",
            "heart_rate",
            "temperature",
            "creatinine",
            "bun",
        ),
        action_terms={
            "insulin": INSULIN_TERMS,
            "dextrose": DEXTROSE_TERMS,
            "fluids": FLUID_TERMS,
            "potassium_repletion": POTASSIUM_REPLETION_TERMS,
            "systemic_steroid": SYSTEMIC_STEROID_TERMS,
            "vasopressor": VASOPRESSOR_TERMS,
        },
        active_low={"glucose": 70.0, "cortisol": 5.0, "map": 65.0, "temperature": 35.0},
        active_high={"glucose": 250.0, "serum_osmolality": 310.0, "serum_ketones": 1.0, "anion_gap": 16.0, "tsh": 20.0, "free_t4": 2.5, "temperature": 39.0},
        active_actions=("hist_insulin", "hist_dextrose", "hist_systemic_steroid"),
        notes=(
            "Extends endocrine coverage beyond DKA using glycemic, osmotic, thyroid, and adrenal proxies.",
            "No insulin, steroid, or thyroid-treatment effect claim is allowed.",
        ),
    ),
    "gi_pancreatic_nutrition": BodySystemDiseaseConfig(
        name="gi_pancreatic_nutrition",
        display_name="GI / pancreatic / nutrition failure",
        body_system="gastrointestinal_pancreatic_nutrition",
        diagnosis_patterns=(
            "pancreatitis",
            "gastrointestinal",
            "malnutrition",
            "nutrition",
            "ileus",
            "bowel",
            "colitis",
            "gastritis",
            "peptic ulcer",
            "upper gi",
            "lower gi",
            "k85",
            "k86",
            "k90",
            "k92",
            "577",
        ),
        targets=(
            "lipase",
            "amylase",
            "triglycerides",
            "albumin",
            "prealbumin",
            "total_protein",
            "calcium",
            "glucose",
            "lactate",
            "map",
            "bilirubin",
        ),
        state_vars=(
            "lipase",
            "amylase",
            "triglycerides",
            "albumin",
            "prealbumin",
            "total_protein",
            "calcium",
            "ionized_calcium",
            "glucose",
            "lactate",
            "map",
            "bilirubin",
            "bilirubin_direct",
            "ast",
            "alt",
            "alkaline_phos",
            "wbc",
            "bicarbonate",
            "ph",
            "creatinine",
        ),
        action_terms={
            "fluids": FLUID_TERMS,
            "nutrition": NUTRITION_TERMS,
            "ppi": PPI_TERMS,
            "octreotide": OCTREOTIDE_TERMS,
            "albumin": ALBUMIN_TERMS,
            "antibiotics": ANTIBIOTIC_TERMS,
            "vasopressor": VASOPRESSOR_TERMS,
            "insulin": INSULIN_TERMS,
        },
        active_low={"albumin": 2.5, "prealbumin": 10.0, "calcium": 7.5, "map": 65.0},
        active_high={"lipase": 180.0, "amylase": 180.0, "triglycerides": 500.0, "lactate": 2.0, "bilirubin": 2.0, "glucose": 250.0},
        active_actions=("hist_nutrition", "hist_ppi", "hist_octreotide"),
        notes=(
            "GI/pancreatic/nutrition module uses lab proxies available in ICU EHR.",
            "No nutrition, PPI, octreotide, or feeding recommendation claim is allowed.",
        ),
    ),
    "cardiac_injury": BodySystemDiseaseConfig(
        name="cardiac_injury",
        display_name="Cardiac injury / myocardial stress biomarkers",
        body_system="cardiac_myocardial",
        diagnosis_patterns=(
            "myocardial infarction",
            "acute coronary",
            "nstemi",
            "stemi",
            "troponin",
            "myocarditis",
            "cardiac injury",
            "heart failure",
            "cardiomyopathy",
            "cardiac arrest",
            "410",
            "411",
            "412",
            "i21",
            "i22",
            "i50",
        ),
        targets=(
            "troponin_i",
            "troponin_t",
            "bnp",
            "ck_mb",
            "ck_mb_index",
            "cpk",
            "map",
            "heart_rate",
            "lactate",
            "potassium",
            "creatinine",
        ),
        state_vars=(
            "troponin_i",
            "troponin_t",
            "bnp",
            "ck_mb",
            "ck_mb_index",
            "cpk",
            "ldh",
            "map",
            "heart_rate",
            "lactate",
            "potassium",
            "sodium",
            "bicarbonate",
            "ph",
            "creatinine",
            "bun",
            "o2sat",
            "respiratory_rate",
        ),
        action_terms={
            "vasopressor": VASOPRESSOR_TERMS,
            "inotrope": INOTROPE_TERMS,
            "antiarrhythmic": ANTIARRHYTHMIC_TERMS,
            "anticoagulant": ANTICOAGULANT_TERMS,
            "antiplatelet": ANTIPLATELET_TERMS,
            "diuretics": DIURETIC_TERMS,
            "fluids": FLUID_TERMS,
            "ventilation": VENTILATION_TERMS,
        },
        active_low={"map": 65.0, "o2sat": 92.0},
        active_high={"troponin_i": 0.1, "troponin_t": 0.1, "bnp": 500.0, "ck_mb": 10.0, "cpk": 1000.0, "lactate": 2.0, "heart_rate": 120.0},
        active_actions=("hist_vasopressor", "hist_inotrope", "hist_antiarrhythmic"),
        notes=(
            "Separates myocardial biomarker forecasting from the broader hemodynamic cardiovascular module.",
            "No ACS, anticoagulation, or catheterization treatment-effect claim is allowed.",
        ),
    ),
    "musculoskeletal_rhabdo": BodySystemDiseaseConfig(
        name="musculoskeletal_rhabdo",
        display_name="Musculoskeletal injury / rhabdomyolysis",
        body_system="musculoskeletal",
        diagnosis_patterns=(
            "rhabdomyolysis",
            "rhabdo",
            "crush",
            "compartment syndrome",
            "muscle injury",
            "myopathy",
            "trauma",
            "burn",
            "728.88",
            "m62",
            "t79.6",
        ),
        targets=(
            "cpk",
            "myoglobin",
            "ldh",
            "potassium",
            "creatinine",
            "bun",
            "phosphate",
            "calcium",
            "bicarbonate",
            "urine_output",
            "map",
        ),
        state_vars=(
            "cpk",
            "myoglobin",
            "ldh",
            "potassium",
            "creatinine",
            "bun",
            "phosphate",
            "calcium",
            "ionized_calcium",
            "bicarbonate",
            "ph",
            "urine_output",
            "map",
            "lactate",
            "sodium",
            "chloride",
        ),
        action_terms={
            "fluids": FLUID_TERMS,
            "bicarbonate": BICARBONATE_TERMS,
            "renal_replacement": RENAL_REPLACEMENT_TERMS,
            "diuretics": DIURETIC_TERMS,
            "calcium_repletion": CALCIUM_REPLETION_TERMS,
            "potassium_repletion": POTASSIUM_REPLETION_TERMS,
            "vasopressor": VASOPRESSOR_TERMS,
        },
        active_low={"urine_output": 30.0, "calcium": 7.5, "map": 65.0, "bicarbonate": 18.0},
        active_high={"cpk": 1000.0, "myoglobin": 500.0, "ldh": 500.0, "potassium": 5.5, "creatinine": 2.0, "phosphate": 5.0},
        active_actions=("hist_fluids", "hist_renal_replacement"),
        notes=(
            "Muscle injury coverage uses CPK/myoglobin/LDH and renal/electrolyte downstream targets.",
            "No fluid or bicarbonate treatment-effect claim is allowed.",
        ),
    ),
    "immune_inflammatory": BodySystemDiseaseConfig(
        name="immune_inflammatory",
        display_name="Immune / inflammatory activation",
        body_system="immune_inflammatory",
        diagnosis_patterns=(
            "inflammatory",
            "autoimmune",
            "lupus",
            "vasculitis",
            "rheumatoid",
            "cytokine",
            "hlh",
            "fever",
            "sirs",
            "immunosuppression",
            "d89",
            "m32",
            "m31",
            "m06",
        ),
        targets=(
            "crp",
            "crp_hs",
            "esr",
            "ferritin",
            "wbc",
            "temperature",
            "lactate",
            "platelets",
            "albumin",
            "map",
        ),
        state_vars=(
            "crp",
            "crp_hs",
            "esr",
            "ferritin",
            "wbc",
            "temperature",
            "lactate",
            "platelets",
            "albumin",
            "map",
            "heart_rate",
            "respiratory_rate",
            "o2sat",
            "creatinine",
            "bilirubin",
            "glucose",
        ),
        action_terms={
            "antibiotics": ANTIBIOTIC_TERMS,
            "systemic_steroid": SYSTEMIC_STEROID_TERMS,
            "fluids": FLUID_TERMS,
            "vasopressor": VASOPRESSOR_TERMS,
            "anticoagulant": ANTICOAGULANT_TERMS,
        },
        active_low={"platelets": 100.0, "albumin": 2.5, "map": 65.0},
        active_high={"crp": 50.0, "crp_hs": 50.0, "esr": 50.0, "ferritin": 1000.0, "wbc": 12.0, "temperature": 38.5, "lactate": 2.0},
        active_actions=("hist_systemic_steroid", "hist_antibiotics", "hist_vasopressor"),
        notes=(
            "Immune/inflammatory module uses sparse inflammatory markers plus dense physiologic proxies.",
            "No immunosuppression, steroid, or antibiotic treatment-effect claim is allowed.",
        ),
    ),
    "cardiovascular_instability": BodySystemDiseaseConfig(
        name="cardiovascular_instability",
        display_name="Cardiovascular instability / shock / heart failure",
        body_system="cardiovascular",
        diagnosis_patterns=(
            "cardiogenic shock",
            "shock, cardiogenic",
            "heart failure",
            "congestive heart failure",
            "acute coronary",
            "myocardial infarction",
            "cardiac arrest",
            "arrhythmia",
            "atrial fibrillation",
            "428",
            "410",
            "i50",
            "i21",
            "i46",
            "i48",
        ),
        targets=(
            "map",
            "heart_rate",
            "lactate",
            "creatinine",
            "urine_output",
            "potassium",
            "bicarbonate",
        ),
        state_vars=(
            "map",
            "heart_rate",
            "lactate",
            "creatinine",
            "urine_output",
            "potassium",
            "bicarbonate",
            "ph",
            "sodium",
            "o2sat",
            "respiratory_rate",
            "temperature",
            "glucose",
        ),
        action_terms={
            "vasopressor": VASOPRESSOR_TERMS,
            "inotrope": INOTROPE_TERMS,
            "fluids": FLUID_TERMS,
            "diuretics": DIURETIC_TERMS,
            "antiarrhythmic": ANTIARRHYTHMIC_TERMS,
            "ventilation": VENTILATION_TERMS,
        },
        active_low={"map": 65.0, "urine_output": 30.0},
        active_high={"lactate": 2.0, "heart_rate": 120.0, "creatinine": 2.0},
        active_actions=("hist_vasopressor", "hist_inotrope"),
        notes=(
            "Covers hemodynamic factual forecasting, not treatment-effect estimation.",
            "Vasopressor/inotrope claims remain observational and fail-closed for causality.",
        ),
    ),
    "acute_neuro": BodySystemDiseaseConfig(
        name="acute_neuro",
        display_name="Acute neurologic injury / seizure / coma",
        body_system="nervous_system",
        diagnosis_patterns=(
            "stroke",
            "cerebrovascular accident",
            "intracranial hemorrhage",
            "subarachnoid",
            "subdural",
            "seizure",
            "status epilepticus",
            "coma",
            "encephalopathy",
            "traumatic brain",
            "i63",
            "i61",
            "i60",
            "r56",
            "g40",
        ),
        targets=(
            "map",
            "heart_rate",
            "respiratory_rate",
            "o2sat",
            "glucose",
            "sodium",
            "ph",
        ),
        state_vars=(
            "map",
            "heart_rate",
            "respiratory_rate",
            "o2sat",
            "glucose",
            "sodium",
            "ph",
            "bicarbonate",
            "potassium",
            "creatinine",
            "temperature",
            "wbc",
        ),
        action_terms={
            "ventilation": VENTILATION_TERMS,
            "vasopressor": VASOPRESSOR_TERMS,
            "antiepileptic": ANTIEPILEPTIC_TERMS,
            "osmotherapy": OSMOTHERAPY_TERMS,
            "fluids": FLUID_TERMS,
        },
        active_low={"o2sat": 92.0, "map": 65.0, "glucose": 70.0, "ph": 7.30},
        active_high={"respiratory_rate": 24.0, "glucose": 250.0, "sodium": 150.0},
        active_actions=("hist_ventilation", "hist_antiepileptic", "hist_osmotherapy"),
        notes=(
            "ICU EHR does not expose neurologic exam granularity reliably; targets are physiologic proxies.",
            "No neurologic outcome or treatment-effect claim is allowed.",
        ),
    ),
    "hepatic_failure": BodySystemDiseaseConfig(
        name="hepatic_failure",
        display_name="Hepatic failure / cirrhosis / hepatic encephalopathy",
        body_system="hepatic_gastrointestinal",
        diagnosis_patterns=(
            "liver failure",
            "hepatic failure",
            "cirrhosis",
            "hepatic encephalopathy",
            "acute liver",
            "alcoholic hepatitis",
            "shock liver",
            "liver disease",
            "k72",
            "k74",
            "570",
            "571",
        ),
        targets=(
            "bilirubin",
            "bilirubin_direct",
            "platelets",
            "lactate",
            "bicarbonate",
            "creatinine",
            "map",
        ),
        state_vars=(
            "bilirubin",
            "bilirubin_direct",
            "platelets",
            "lactate",
            "bicarbonate",
            "creatinine",
            "map",
            "bun",
            "sodium",
            "potassium",
            "ph",
            "wbc",
            "glucose",
            "heart_rate",
        ),
        action_terms={
            "fluids": FLUID_TERMS,
            "vasopressor": VASOPRESSOR_TERMS,
            "antibiotics": ANTIBIOTIC_TERMS,
            "renal_replacement": RENAL_REPLACEMENT_TERMS,
            "hepatic_encephalopathy_tx": HEPATIC_ENCEPHALOPATHY_TERMS,
        },
        active_low={"platelets": 100.0, "map": 65.0},
        active_high={"bilirubin": 2.0, "lactate": 2.0, "creatinine": 2.0},
        active_actions=("hist_vasopressor", "hist_renal_replacement"),
        notes=(
            "Coagulation labs are incomplete in the current eICU state map; bilirubin/platelets are proxies.",
            "No transplant, bleeding, or encephalopathy treatment-effect claim is allowed.",
        ),
    ),
    "coagulopathy_heme": BodySystemDiseaseConfig(
        name="coagulopathy_heme",
        display_name="Coagulopathy / thrombocytopenia / hematologic instability",
        body_system="hematologic",
        diagnosis_patterns=(
            "thrombocytopenia",
            "coagulopathy",
            "disseminated intravascular",
            "dic",
            "anemia",
            "hemorrhage",
            "gastrointestinal bleeding",
            "gi bleed",
            "bleeding",
            "d65",
            "d69",
            "d62",
            "285",
            "286",
        ),
        targets=(
            "platelets",
            "hemoglobin",
            "hematocrit",
            "inr",
            "ptt",
            "fibrinogen",
            "wbc",
            "lactate",
            "map",
            "bicarbonate",
            "ph",
            "creatinine",
        ),
        state_vars=(
            "platelets",
            "hemoglobin",
            "hematocrit",
            "inr",
            "ptt",
            "fibrinogen",
            "wbc",
            "lactate",
            "map",
            "bicarbonate",
            "ph",
            "creatinine",
            "bun",
            "potassium",
            "sodium",
            "heart_rate",
            "temperature",
            "glucose",
        ),
        action_terms={
            "transfusion": TRANSFUSION_TERMS,
            "anticoagulant": ANTICOAGULANT_TERMS,
            "antiplatelet": ANTIPLATELET_TERMS,
            "fluids": FLUID_TERMS,
            "vasopressor": VASOPRESSOR_TERMS,
            "antibiotics": ANTIBIOTIC_TERMS,
            "nephrotoxin": NEPHROTOXIN_TERMS,
        },
        active_low={"platelets": 100.0, "hemoglobin": 8.0, "map": 65.0, "ph": 7.30},
        active_high={"inr": 1.5, "ptt": 45.0, "lactate": 2.0, "wbc": 12.0, "creatinine": 2.0},
        active_actions=("hist_transfusion", "hist_vasopressor"),
        notes=(
            "Hemoglobin, hematocrit, INR, PTT, fibrinogen, and transfusion evidence are first-class inputs.",
            "Transfusion and anticoagulation effects remain causal-closed.",
        ),
    ),
}


def get_body_system_config(name: str) -> BodySystemDiseaseConfig:
    try:
        return BODY_SYSTEM_CONFIGS[name]
    except KeyError as exc:
        available = ", ".join(sorted(BODY_SYSTEM_CONFIGS))
        raise ValueError(f"unknown body-system disease '{name}'. Available: {available}") from exc
