"""Cross-fitted real-world adaptation and calibration experiments for DKA JEPA.

No additional records are introduced. Every reported prediction is generated by
an adapter that did not train on that patient stay. The resulting artifact is a
research domain adapter, not a causal estimator or clinical model.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import torch
from scipy.optimize import minimize_scalar
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.model_selection import GroupKFold

from dka_world_model import (
    ACTION_KEYS, A_DIM, DT, S_DIM, S_MEAN, S_STD, STATE_KEYS, load_checkpoint,
    s2vec,
)
from osler_jepa.symbolic import PHYSICAL_STABLE_THRESHOLDS
from symbolic_real_test import _action_data, _actual_directions, _state_from_row
from train_intervention_jepa import choose_device


TARGET_COLUMNS = {
    0: ("glucose_t", "glucose_tp6"),
    1: ("ph_t", "ph_tp6"),
    2: ("bicarbonate_t", "bicarbonate_tp6"),
    3: ("anion_gap_t", "anion_gap_tp6"),
    4: ("potassium_t", "potassium_tp6"),
    5: ("map_t", "map_tp6"),
    8: ("sodium_t", "sodium_tp6"),
    9: ("osmolality_t", "osmolality_tp6"),
    10: ("creatinine_t", "creatinine_tp6"),
    11: ("urine_output_t", "urine_output_tp6"),
}
ADAPTED_STATE_INDICES = tuple(TARGET_COLUMNS)
WEIGHT_MODES = ("unweighted", "episode", "propensity", "combined")
RIDGE_ALPHAS = (0.1, 1.0, 10.0, 100.0)


def _value(row, name, default=np.nan):
    value = row.get(name, default)
    return default if pd.isna(value) else float(value)


def target_vector(row):
    target = np.full(S_DIM, np.nan, dtype=np.float32)
    for index, (_, target_column) in TARGET_COLUMNS.items():
        value = _value(row, target_column)
        if index == 9 and np.isnan(value):
            value = _value(row, "osmolality_derived_tp6")
        if index == 1 and np.isnan(value):
            bicarbonate = _value(row, "bicarbonate_tp6")
            if not np.isnan(bicarbonate):
                value = 6.1 + np.log10(max(bicarbonate, 0.1) / 1.2)
        target[index] = value
    return target


def episode_features(sequence):
    active = sequence > 0.05
    action_exposure = sequence.mean(axis=0)
    active_channels = int((action_exposure > 0.05).sum())
    total = float(action_exposure.sum())
    purity = float(action_exposure.max() / total) if total > 0 else 0.0
    simultaneous = float((active.sum(axis=1) > 1).mean())
    isolated = float(active_channels == 1 and simultaneous == 0.0)
    return action_exposure, np.array(
        [active_channels / A_DIM, purity, simultaneous, isolated],
        dtype=np.float32,
    )


@torch.no_grad()
def build_examples(model, frame, device):
    examples = []
    age_columns = [
        "glucose_age_hr", "ph_age_hr", "bicarbonate_age_hr",
        "anion_gap_age_hr", "potassium_age_hr", "map_age_hr",
        "sodium_age_hr", "osmolality_age_hr", "creatinine_age_hr",
        "urine_output_age_hr",
    ]
    for row_index, row in frame.iterrows():
        state = _state_from_row(row)
        sequence, history = _action_data(row)
        if state is None or sequence is None:
            continue
        state_normalized = s2vec(state)
        history = np.zeros(A_DIM * 2, dtype=np.float32) if history is None else np.asarray(
            history, dtype=np.float32
        )
        state_tensor = torch.as_tensor(
            state_normalized, dtype=torch.float32, device=device
        ).unsqueeze(0)
        history_tensor = torch.as_tensor(
            history, dtype=torch.float32, device=device
        ).unsqueeze(0)
        predicted, _, _ = model.rollout(
            state_tensor,
            torch.as_tensor(sequence, dtype=torch.float32, device=device).unsqueeze(0),
            history_tensor,
        )
        base_normalized = predicted[0, -1].cpu().numpy()
        base_physical = base_normalized * S_STD + S_MEAN
        target = target_vector(row)
        action_exposure, episode = episode_features(sequence)
        ages = np.asarray([
            min(_value(row, column, 6.0), 24.0) / 24.0
            for column in age_columns
        ], dtype=np.float32)
        dka_active = bool(row.get("dka_active_t", False))
        time_from_onset = min(max(_value(row, "hours_since_onset", 0.0), 0.0), 72.0) / 72.0
        adapter_features = np.concatenate([
            state_normalized,
            base_normalized - state_normalized,
            action_exposure,
            history,
            episode,
            ages,
            np.asarray([float(dka_active), time_from_onset], dtype=np.float32),
        ]).astype(np.float32)
        propensity_features = np.concatenate([
            state_normalized,
            history,
            ages,
            np.asarray([float(dka_active), time_from_onset], dtype=np.float32),
        ]).astype(np.float32)
        actual_directions = _actual_directions(row, state)
        latent = model.encode_state(state_tensor, history_tensor)
        symbolic = model.symbolic_outputs(
            latent,
            torch.as_tensor(
                action_exposure, dtype=torch.float32, device=device
            ).unsqueeze(0),
            delta_hours=sequence.shape[0] * DT,
        )
        examples.append({
            "row_index": int(row_index),
            "subject_id": int(row["subject_id"]),
            "stay_id": int(row["stay_id"]),
            "active_dka": dka_active,
            "current_physical": np.asarray([
                state[name] for name in STATE_KEYS
            ], dtype=np.float32),
            "base_physical": base_physical.astype(np.float32),
            "target_physical": target,
            "adapter_features": adapter_features,
            "propensity_features": propensity_features,
            "action_exposure": action_exposure.astype(np.float32),
            "action_active": (action_exposure > 0.05).astype(np.int64),
            "episode_weight": float(0.25 + 0.75 * episode[1] / (1.0 + episode[2])),
            "episode": episode,
            "actual_directions": actual_directions,
            "symbolic_probabilities": symbolic["proposal_logits"].softmax(
                dim=-1
            )[0].cpu().numpy(),
        })
    return examples


def arrays(examples):
    return {
        "x": np.stack([item["adapter_features"] for item in examples]),
        "propensity_x": np.stack([
            item["propensity_features"] for item in examples
        ]),
        "actions": np.stack([item["action_active"] for item in examples]),
        "base": np.stack([item["base_physical"] for item in examples]),
        "current": np.stack([item["current_physical"] for item in examples]),
        "target": np.stack([item["target_physical"] for item in examples]),
        "episode_weight": np.asarray([
            item["episode_weight"] for item in examples
        ], dtype=np.float32),
        "groups": np.asarray([item["stay_id"] for item in examples]),
        "active": np.asarray([item["active_dka"] for item in examples]),
    }


def standardize(train_x, other_x):
    mean = train_x.mean(axis=0)
    std = train_x.std(axis=0)
    std[std < 1e-6] = 1.0
    return (train_x - mean) / std, (other_x - mean) / std, mean, std


def propensity_overlap_weights(propensity_x, actions, indices):
    x = propensity_x[indices]
    labels = actions[indices]
    x_scaled, _, _, _ = standardize(x, x)
    channel_weights = []
    for action_index in range(A_DIM):
        y = labels[:, action_index]
        if len(np.unique(y)) < 2 or min(np.bincount(y)) < 2:
            channel_weights.append(np.ones(len(indices), dtype=np.float32))
            continue
        model = LogisticRegression(C=0.25, max_iter=1000, class_weight="balanced")
        model.fit(x_scaled, y)
        probability = np.clip(model.predict_proba(x_scaled)[:, 1], 0.05, 0.95)
        overlap = np.where(y == 1, 1.0 - probability, probability)
        channel_weights.append(overlap.astype(np.float32))
    weights = np.mean(np.stack(channel_weights, axis=1), axis=1)
    return np.clip(weights / max(weights.mean(), 1e-6), 0.25, 4.0)


def fitting_weights(data, indices, mode):
    if mode == "unweighted":
        return np.ones(len(indices), dtype=np.float32)
    episode = data["episode_weight"][indices]
    if mode == "episode":
        return episode / max(episode.mean(), 1e-6)
    propensity = propensity_overlap_weights(
        data["propensity_x"], data["actions"], indices
    )
    if mode == "propensity":
        return propensity
    combined = propensity * episode
    return combined / max(combined.mean(), 1e-6)


def fit_ridge(data, train_indices, target_index, mode, alpha):
    observed = np.isfinite(data["target"][train_indices, target_index])
    selected = train_indices[observed]
    if len(selected) < 8 or len(np.unique(data["groups"][selected])) < 3:
        return None
    x = data["x"][selected]
    mean = x.mean(axis=0)
    std = x.std(axis=0)
    std[std < 1e-6] = 1.0
    y = (
        data["target"][selected, target_index]
        - data["base"][selected, target_index]
    ) / S_STD[target_index]
    all_weights = fitting_weights(data, train_indices, mode)
    weight_lookup = dict(zip(train_indices.tolist(), all_weights.tolist()))
    weights = np.asarray([weight_lookup[index] for index in selected])
    model = Ridge(alpha=alpha)
    model.fit((x - mean) / std, y, sample_weight=weights)
    return {"model": model, "mean": mean, "std": std}


def predict_ridge(fitted, data, indices, target_index):
    if fitted is None:
        return data["base"][indices, target_index]
    correction = fitted["model"].predict(
        (data["x"][indices] - fitted["mean"]) / fitted["std"]
    )
    return data["base"][indices, target_index] + correction * S_STD[target_index]


def choose_configuration(data, outer_train, target_index):
    observed = np.isfinite(data["target"][outer_train, target_index])
    candidates = outer_train[observed]
    groups = data["groups"][candidates]
    unique_groups = np.unique(groups)
    if len(candidates) < 10 or len(unique_groups) < 4:
        return "unweighted", 100.0
    splitter = GroupKFold(n_splits=min(4, len(unique_groups)))
    scores = defaultdict(list)
    for inner_train_local, inner_validation_local in splitter.split(
        candidates, groups=groups
    ):
        inner_train = candidates[inner_train_local]
        inner_validation = candidates[inner_validation_local]
        for mode in WEIGHT_MODES:
            for alpha in RIDGE_ALPHAS:
                fitted = fit_ridge(
                    data, inner_train, target_index, mode, alpha
                )
                prediction = predict_ridge(
                    fitted, data, inner_validation, target_index
                )
                truth = data["target"][inner_validation, target_index]
                scores[(mode, alpha)].extend(np.abs(prediction - truth).tolist())
    return min(scores, key=lambda key: np.mean(scores[key]))


def choose_safe_method(data, outer_train, target_index,
                       validation_active_only=False):
    """Select persistence, raw JEPA, or adapter using inner patient CV only."""
    observed = np.isfinite(data["target"][outer_train, target_index])
    candidates = outer_train[observed]
    groups = data["groups"][candidates]
    unique_groups = np.unique(groups)
    if len(candidates) < 10 or len(unique_groups) < 4:
        return "persistence", None, None
    splitter = GroupKFold(n_splits=min(4, len(unique_groups)))
    scores = defaultdict(list)
    for inner_train_local, inner_validation_local in splitter.split(
        candidates, groups=groups
    ):
        inner_train = candidates[inner_train_local]
        inner_validation = candidates[inner_validation_local]
        if validation_active_only:
            inner_validation = inner_validation[data["active"][inner_validation]]
            if len(inner_validation) == 0:
                continue
        truth = data["target"][inner_validation, target_index]
        scores[("persistence", None, None)].extend(np.abs(
            data["current"][inner_validation, target_index] - truth
        ).tolist())
        scores[("base_jepa", None, None)].extend(np.abs(
            data["base"][inner_validation, target_index] - truth
        ).tolist())
        for mode in WEIGHT_MODES:
            for alpha in RIDGE_ALPHAS:
                fitted = fit_ridge(
                    data, inner_train, target_index, mode, alpha
                )
                prediction = predict_ridge(
                    fitted, data, inner_validation, target_index
                )
                scores[("adapter", mode, alpha)].extend(
                    np.abs(prediction - truth).tolist()
                )
    if not scores:
        return "persistence", None, None
    return min(scores, key=lambda key: np.mean(scores[key]))


def choose_alpha_for_mode(data, outer_train, target_index, mode):
    observed = np.isfinite(data["target"][outer_train, target_index])
    candidates = outer_train[observed]
    groups = data["groups"][candidates]
    unique_groups = np.unique(groups)
    if len(candidates) < 10 or len(unique_groups) < 4:
        return 100.0
    splitter = GroupKFold(n_splits=min(4, len(unique_groups)))
    scores = defaultdict(list)
    for inner_train_local, inner_validation_local in splitter.split(
        candidates, groups=groups
    ):
        inner_train = candidates[inner_train_local]
        inner_validation = candidates[inner_validation_local]
        truth = data["target"][inner_validation, target_index]
        for alpha in RIDGE_ALPHAS:
            fitted = fit_ridge(data, inner_train, target_index, mode, alpha)
            prediction = predict_ridge(
                fitted, data, inner_validation, target_index
            )
            scores[alpha].extend(np.abs(prediction - truth).tolist())
    return min(scores, key=lambda alpha: np.mean(scores[alpha]))


def fit_ensemble(data, train_indices, target_index, mode, alpha, rng,
                 members=20):
    models = []
    main = fit_ridge(data, train_indices, target_index, mode, alpha)
    if main is not None:
        models.append(main)
    groups = np.unique(data["groups"][train_indices])
    for _ in range(members - 1):
        sampled_groups = rng.choice(groups, size=len(groups), replace=True)
        sampled = np.concatenate([
            train_indices[data["groups"][train_indices] == group]
            for group in sampled_groups
        ])
        fitted = fit_ridge(data, sampled, target_index, mode, alpha)
        if fitted is not None:
            models.append(fitted)
    return models


def ensemble_predict(models, data, indices, target_index):
    if not models:
        prediction = data["base"][indices, target_index]
        return prediction, np.zeros_like(prediction), np.ones_like(prediction)
    predictions = np.stack([
        predict_ridge(model, data, indices, target_index) for model in models
    ])
    mean = predictions.mean(axis=0)
    std = predictions.std(axis=0)
    threshold = PHYSICAL_STABLE_THRESHOLDS[target_index]
    current = data["current"][indices, target_index]
    directions = np.where(
        predictions - current < -threshold, 0,
        np.where(predictions - current > threshold, 2, 1),
    )
    agreement = np.max(np.stack([
        (directions == direction).mean(axis=0) for direction in (0, 1, 2)
    ]), axis=0)
    return mean, std, agreement


def direction(values, current, target_index):
    threshold = PHYSICAL_STABLE_THRESHOLDS[target_index]
    delta = values - current
    return np.where(delta < -threshold, 0, np.where(delta > threshold, 2, 1))


def temperature_scale(probabilities, labels):
    if len(labels) < 10:
        return 1.0
    logits = np.log(np.clip(probabilities, 1e-7, 1.0))

    def objective(log_temperature):
        temperature = np.exp(log_temperature)
        scaled = logits / temperature
        scaled -= scaled.max(axis=1, keepdims=True)
        probability = np.exp(scaled)
        probability /= probability.sum(axis=1, keepdims=True)
        return -float(np.log(probability[np.arange(len(labels)), labels] + 1e-12).mean())

    result = minimize_scalar(objective, bounds=(-3.0, 4.0), method="bounded")
    return float(np.exp(result.x))


def apply_temperature(probabilities, temperature):
    logits = np.log(np.clip(probabilities, 1e-7, 1.0)) / temperature
    logits -= logits.max(axis=-1, keepdims=True)
    scaled = np.exp(logits)
    return scaled / scaled.sum(axis=-1, keepdims=True)


def expected_calibration_error(probabilities, labels, bins=8):
    confidence = probabilities.max(axis=1)
    prediction = probabilities.argmax(axis=1)
    correct = prediction == labels
    ece = 0.0
    for low, high in zip(np.linspace(0, 1, bins + 1)[:-1],
                         np.linspace(0, 1, bins + 1)[1:]):
        selected = (confidence > low) & (confidence <= high)
        if selected.any():
            ece += selected.mean() * abs(
                confidence[selected].mean() - correct[selected].mean()
            )
    return float(ece)


def probability_metrics(probabilities, labels):
    prediction = probabilities.argmax(axis=1)
    one_hot = np.eye(3)[labels]
    return {
        "n": int(len(labels)),
        "accuracy": round(float((prediction == labels).mean()), 4),
        "mean_confidence": round(float(probabilities.max(axis=1).mean()), 4),
        "ece": round(expected_calibration_error(probabilities, labels), 4),
        "brier": round(float(((probabilities - one_hot) ** 2).sum(axis=1).mean()), 4),
    }


def bootstrap_mae_difference(rows, method, baseline, active_only=True,
                             seed=7, samples=2000):
    relevant = [row for row in rows if (row["active_dka"] or not active_only)]
    stays = sorted({row["stay_id"] for row in relevant})
    rng = np.random.default_rng(seed)
    differences = []
    for _ in range(samples):
        selected_stays = rng.choice(stays, size=len(stays), replace=True)
        method_errors = []
        baseline_errors = []
        for stay in selected_stays:
            for row in relevant:
                if row["stay_id"] != stay or not np.isfinite(row["truth"]):
                    continue
                method_errors.append(abs(row[method] - row["truth"]) / row["scale"])
                baseline_errors.append(abs(row[baseline] - row["truth"]) / row["scale"])
        if method_errors:
            differences.append(np.mean(method_errors) - np.mean(baseline_errors))
    if not differences:
        return None
    return {
        "normalized_mae_difference": round(float(np.mean(differences)), 5),
        "bootstrap_95_ci": [
            round(float(np.quantile(differences, 0.025)), 5),
            round(float(np.quantile(differences, 0.975)), 5),
        ],
    }


def summarize_numerical(rows, active_only):
    selected = [row for row in rows if row["active_dka"] or not active_only]
    report = {}
    for method in (
        "persistence", "base_jepa", "adapter", "ensemble_adapter",
        "safe_hybrid", "active_safe_hybrid"
    ):
        errors = [
            abs(row[method] - row["truth"]) / row["scale"]
            for row in selected if np.isfinite(row["truth"])
        ]
        report[method] = {
            "n": len(errors),
            "normalized_mae": round(float(np.mean(errors)), 5) if errors else None,
        }
    per_state = {}
    for target_index in ADAPTED_STATE_INDICES:
        name = STATE_KEYS[target_index]
        state_rows = [row for row in selected if row["target_index"] == target_index]
        values = {}
        for method in (
            "persistence", "base_jepa", "ensemble_adapter", "safe_hybrid",
            "active_safe_hybrid"
        ):
            errors = [abs(row[method] - row["truth"]) for row in state_rows]
            values[method] = round(float(np.mean(errors)), 4) if errors else None
        per_state[name] = {"n": len(state_rows), **values}
    report["per_state_mae"] = per_state
    report["adapter_vs_base_jepa"] = bootstrap_mae_difference(
        rows, "ensemble_adapter", "base_jepa", active_only=active_only
    )
    report["adapter_vs_persistence"] = bootstrap_mae_difference(
        rows, "ensemble_adapter", "persistence", active_only=active_only
    )
    report["safe_hybrid_vs_base_jepa"] = bootstrap_mae_difference(
        rows, "safe_hybrid", "base_jepa", active_only=active_only
    )
    report["safe_hybrid_vs_persistence"] = bootstrap_mae_difference(
        rows, "safe_hybrid", "persistence", active_only=active_only
    )
    report["active_safe_hybrid_vs_persistence"] = bootstrap_mae_difference(
        rows, "active_safe_hybrid", "persistence", active_only=active_only
    )
    return report


def summarize_ablation(rows, active_only):
    selected = [row for row in rows if row["active_dka"] or not active_only]
    methods = [
        "persistence", "base_jepa",
        *[f"ensemble_{mode}" for mode in WEIGHT_MODES],
    ]
    return {
        method: {
            "n": int(sum(bool(np.isfinite(row["truth"])) for row in selected)),
            "normalized_mae": round(float(np.mean([
                abs(row[method] - row["truth"]) / row["scale"]
                for row in selected if np.isfinite(row["truth"])
            ])), 5),
        }
        for method in methods
    }


def run_crossfit(examples, seed=17):
    data = arrays(examples)
    unique_stays = np.unique(data["groups"])
    splitter = GroupKFold(n_splits=min(4, len(unique_stays)))
    rng = np.random.default_rng(seed)
    numerical_rows = []
    symbolic_before = []
    symbolic_after = []
    symbolic_labels = []
    symbolic_changed = []
    symbolic_stays = []
    configurations = Counter()
    safe_configurations = Counter()
    active_safe_configurations = Counter()

    for outer_train, outer_test in splitter.split(
        np.arange(len(examples)), groups=data["groups"]
    ):
        test_stays = set(data["groups"][outer_test].tolist())
        if test_stays & set(data["groups"][outer_train].tolist()):
            raise RuntimeError("patient leakage in outer split")

        train_probability = []
        train_label = []
        for index in outer_train:
            directions = examples[index]["actual_directions"]
            for state_index in ADAPTED_STATE_INDICES:
                if directions[state_index] >= 0:
                    train_probability.append(
                        examples[index]["symbolic_probabilities"][state_index]
                    )
                    train_label.append(directions[state_index])
        temperature = temperature_scale(
            np.asarray(train_probability), np.asarray(train_label, dtype=np.int64)
        )

        for target_index in ADAPTED_STATE_INDICES:
            mode, alpha = choose_configuration(data, outer_train, target_index)
            configurations[(STATE_KEYS[target_index], mode, alpha)] += 1
            safe_method, safe_mode, safe_alpha = choose_safe_method(
                data, outer_train, target_index
            )
            active_method, active_mode, active_alpha = choose_safe_method(
                data, outer_train, target_index, validation_active_only=True
            )
            safe_configurations[(
                STATE_KEYS[target_index], safe_method, safe_mode, safe_alpha
            )] += 1
            active_safe_configurations[(
                STATE_KEYS[target_index], active_method, active_mode, active_alpha
            )] += 1
            fitted = fit_ridge(data, outer_train, target_index, mode, alpha)
            ensemble = fit_ensemble(
                data, outer_train, target_index, mode, alpha, rng
            )
            single_prediction = predict_ridge(
                fitted, data, outer_test, target_index
            )
            ensemble_prediction, ensemble_std, agreement = ensemble_predict(
                ensemble, data, outer_test, target_index
            )
            if safe_method == "persistence":
                safe_prediction = data["current"][outer_test, target_index]
            elif safe_method == "base_jepa":
                safe_prediction = data["base"][outer_test, target_index]
            else:
                safe_models = fit_ensemble(
                    data, outer_train, target_index, safe_mode, safe_alpha, rng
                )
                safe_prediction, _, _ = ensemble_predict(
                    safe_models, data, outer_test, target_index
                )
            if active_method == "persistence":
                active_prediction = data["current"][outer_test, target_index]
            elif active_method == "base_jepa":
                active_prediction = data["base"][outer_test, target_index]
            else:
                active_models = fit_ensemble(
                    data, outer_train, target_index,
                    active_mode, active_alpha, rng
                )
                active_prediction, _, _ = ensemble_predict(
                    active_models, data, outer_test, target_index
                )
            active_safe_prediction = np.where(
                data["active"][outer_test], active_prediction, safe_prediction
            )
            ablation_predictions = {}
            for ablation_mode in WEIGHT_MODES:
                ablation_alpha = choose_alpha_for_mode(
                    data, outer_train, target_index, ablation_mode
                )
                ablation_models = fit_ensemble(
                    data, outer_train, target_index,
                    ablation_mode, ablation_alpha, rng
                )
                ablation_predictions[ablation_mode], _, _ = ensemble_predict(
                    ablation_models, data, outer_test, target_index
                )
            for local, index in enumerate(outer_test):
                truth = data["target"][index, target_index]
                if not np.isfinite(truth):
                    continue
                numerical_rows.append({
                    "stay_id": int(data["groups"][index]),
                    "active_dka": bool(data["active"][index]),
                    "target_index": target_index,
                    "state": STATE_KEYS[target_index],
                    "truth": float(truth),
                    "current": float(data["current"][index, target_index]),
                    "scale": float(S_STD[target_index]),
                    "persistence": float(data["current"][index, target_index]),
                    "base_jepa": float(data["base"][index, target_index]),
                    "adapter": float(single_prediction[local]),
                    "ensemble_adapter": float(ensemble_prediction[local]),
                    "safe_hybrid": float(safe_prediction[local]),
                    "active_safe_hybrid": float(active_safe_prediction[local]),
                    **{
                        f"ensemble_{ablation_mode}": float(
                            predictions[local]
                        )
                        for ablation_mode, predictions in ablation_predictions.items()
                    },
                    "ensemble_std": float(ensemble_std[local]),
                    "ensemble_direction_agreement": float(agreement[local]),
                })

        for index in outer_test:
            directions = examples[index]["actual_directions"]
            for state_index in ADAPTED_STATE_INDICES:
                label = int(directions[state_index])
                if label < 0:
                    continue
                before = examples[index]["symbolic_probabilities"][state_index]
                after = apply_temperature(before[None, :], temperature)[0]
                symbolic_before.append(before)
                symbolic_after.append(after)
                symbolic_labels.append(label)
                symbolic_changed.append(label != 1)
                symbolic_stays.append(int(data["groups"][index]))

    return {
        "numerical_rows": numerical_rows,
        "symbolic_before": np.asarray(symbolic_before),
        "symbolic_after": np.asarray(symbolic_after),
        "symbolic_labels": np.asarray(symbolic_labels, dtype=np.int64),
        "symbolic_changed": np.asarray(symbolic_changed, dtype=bool),
        "symbolic_stays": np.asarray(symbolic_stays),
        "configurations": configurations,
        "safe_configurations": safe_configurations,
        "active_safe_configurations": active_safe_configurations,
    }


def abstention_metrics(probabilities, labels, threshold):
    confidence = probabilities.max(axis=1)
    accepted = confidence >= threshold
    prediction = probabilities.argmax(axis=1)
    return {
        "threshold": threshold,
        "coverage": round(float(accepted.mean()), 4),
        "accepted": int(accepted.sum()),
        "accuracy": round(float((prediction[accepted] == labels[accepted]).mean()), 4)
        if accepted.any() else None,
        "abstained": int((~accepted).sum()),
    }


def train_deployment_artifact(examples, data, output, seed=17):
    indices = np.arange(len(examples))
    rng = np.random.default_rng(seed)
    artifact = {
        "version": "1.0.0",
        "warning": (
            "Fitted on all available demo stays after cross-fitted evaluation; "
            "research use only, no causal or clinical claim."
        ),
        "state_keys": STATE_KEYS,
        "action_keys": ACTION_KEYS,
        "models": {},
    }
    probabilities = []
    labels = []
    for example in examples:
        for state_index in ADAPTED_STATE_INDICES:
            label = int(example["actual_directions"][state_index])
            if label >= 0:
                probabilities.append(example["symbolic_probabilities"][state_index])
                labels.append(label)
    artifact["symbolic_calibration"] = {
        "temperature": temperature_scale(
            np.asarray(probabilities), np.asarray(labels, dtype=np.int64)
        ),
        "recommended_min_ensemble_agreement": 0.9,
        "strict_min_ensemble_agreement": 1.0,
        "calibration_scope": "MIMIC-IV demo factual directions",
    }
    for target_index in ADAPTED_STATE_INDICES:
        method, mode, alpha = choose_safe_method(data, indices, target_index)
        models = [] if method != "adapter" else fit_ensemble(
            data, indices, target_index, mode, alpha, rng
        )
        artifact["models"][STATE_KEYS[target_index]] = {
            "target_index": target_index,
            "method": method,
            "mode": mode,
            "alpha": alpha,
            "members": models,
        }
    joblib.dump(artifact, output)
    return artifact


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", default="dka_symbolic_jepa_v5.pt")
    parser.add_argument("--mimic", default="dka_transitions_6h_demo_v4.parquet")
    parser.add_argument("--output", default="dka_real_world_improvement_v1.json")
    parser.add_argument("--artifact", default="dka_real_world_adapter_v1.joblib")
    parser.add_argument("--predictions", default="dka_real_world_oof_predictions_v1.csv")
    parser.add_argument("--seed", type=int, default=17)
    parser.add_argument("--device", default="auto")
    args = parser.parse_args()

    device = choose_device(args.device)
    model, _ = load_checkpoint(args.checkpoint, device)
    frame = pd.read_parquet(args.mimic)
    examples = build_examples(model, frame, device)
    result = run_crossfit(examples, args.seed)
    rows = result["numerical_rows"]
    pd.DataFrame(rows).to_csv(args.predictions, index=False)

    labels = result["symbolic_labels"]
    changed = result["symbolic_changed"]
    before = result["symbolic_before"]
    after = result["symbolic_after"]
    confidence_thresholds = (0.50, 0.60, 0.70, 0.80, 0.90)
    symbolic_report = {
        "all_before": probability_metrics(before, labels),
        "all_after_temperature_scaling": probability_metrics(after, labels),
        "changed_before": probability_metrics(before[changed], labels[changed]),
        "changed_after_temperature_scaling": probability_metrics(
            after[changed], labels[changed]
        ),
        "abstention_changed_only": [
            abstention_metrics(after[changed], labels[changed], threshold)
            for threshold in confidence_thresholds
        ],
    }

    direction_rows = []
    for row in rows:
        truth_direction = int(direction(
            np.asarray([row["truth"]]),
            np.asarray([row["current"]]),
            row["target_index"],
        )[0])
        if truth_direction == 1:
            continue
        row["truth_direction"] = truth_direction
        direction_rows.append(row)
    ensemble_abstention = []
    for threshold in (0.5, 0.6, 0.7, 0.8, 0.9, 1.0):
        accepted = [
            row for row in direction_rows
            if row["ensemble_direction_agreement"] >= threshold
        ]
        correct = []
        for row in accepted:
            prediction_direction = int(direction(
                np.asarray([row["ensemble_adapter"]]),
                np.asarray([row["current"]]), row["target_index"]
            )[0])
            correct.append(prediction_direction == row["truth_direction"])
        ensemble_abstention.append({
            "agreement_threshold": threshold,
            "coverage": round(len(accepted) / max(len(direction_rows), 1), 4),
            "n": len(accepted),
            "changed_direction_accuracy": round(float(np.mean(correct)), 4)
            if correct else None,
        })

    data = arrays(examples)
    artifact = train_deployment_artifact(
        examples, data, args.artifact, args.seed
    )
    configuration_summary = [
        {
            "state": state, "weight_mode": mode, "alpha": alpha,
            "outer_folds_selected": count,
        }
        for (state, mode, alpha), count in sorted(
            result["configurations"].items()
        )
    ]
    safe_configuration_summary = [
        {
            "state": state, "method": method, "weight_mode": mode,
            "alpha": alpha, "outer_folds_selected": count,
        }
        for (state, method, mode, alpha), count in sorted(
            result["safe_configurations"].items(),
            key=lambda item: tuple(str(value) for value in item[0]),
        )
    ]
    active_safe_configuration_summary = [
        {
            "state": state, "method": method, "weight_mode": mode,
            "alpha": alpha, "outer_folds_selected": count,
        }
        for (state, method, mode, alpha), count in sorted(
            result["active_safe_configurations"].items(),
            key=lambda item: tuple(str(value) for value in item[0]),
        )
    ]
    report = {
        "experiment": "no-new-data real-world JEPA improvement",
        "checkpoint": str(Path(args.checkpoint).resolve()),
        "cohort": str(Path(args.mimic).resolve()),
        "evaluation": {
            "type": "4-fold patient-stay cross-fitting",
            "stays": int(frame["stay_id"].nunique()),
            "examples_with_core_state": len(examples),
            "patient_leakage": False,
            "hyperparameter_selection": "inner patient-group cross-validation",
        },
        "methods_tested": [
            "treatment episode purity weighting",
            "per-action propensity overlap weighting",
            "propensity plus episode weighting",
            "ridge real-world residual adapter",
            "20-member patient-bootstrap adapter ensemble",
            "temperature scaling",
            "confidence and ensemble-agreement abstention",
        ],
        "numerical_all_windows": summarize_numerical(rows, active_only=False),
        "numerical_active_dka": summarize_numerical(rows, active_only=True),
        "weighting_ablation_all_windows": summarize_ablation(
            rows, active_only=False
        ),
        "weighting_ablation_active_dka": summarize_ablation(
            rows, active_only=True
        ),
        "symbolic_calibration": symbolic_report,
        "ensemble_abstention_changed_only": ensemble_abstention,
        "selected_configurations": configuration_summary,
        "safe_hybrid_selected_configurations": safe_configuration_summary,
        "active_safe_hybrid_selected_configurations": active_safe_configuration_summary,
        "deployment_artifact": {
            "path": str(Path(args.artifact).resolve()),
            "adapted_states": list(artifact["models"]),
            "trained_on_all_demo_stays_after_evaluation": True,
            "clinical_use_allowed": False,
        },
        "limitations": [
            "No new data were added; only 12 patient stays are available.",
            "Propensity overlap cannot remove unmeasured confounding.",
            "Most DKA episodes contain multiple simultaneous treatments.",
            "Cross-fitted estimates remain high variance at this cohort size.",
            "The deployment artifact has no untouched external validation set.",
        ],
    }
    Path(args.output).write_text(
        json.dumps(report, indent=2, allow_nan=False), encoding="utf-8"
    )
    print(json.dumps(report, indent=2, allow_nan=False))
    print(f"\nsaved report: {args.output}")
    print(f"saved artifact: {args.artifact}")
    print(f"saved OOF predictions: {args.predictions}")


if __name__ == "__main__":
    main()
