"""Train a DKA WorldModel candidate on the synthetic RCT factory output.

This is a simulator-truth training path. It is useful for checking whether the
JEPA architecture can learn the fictional RCT response surface generated by
``synthetic_rct_factory.py``. It must not be interpreted as human treatment
effect evidence, clinical validation, checkpoint promotion, or a replacement
for real randomized data.
"""

from __future__ import annotations

import argparse
import json
import math
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F

from dka_world_model import (
    A_DIM,
    A_SCALE,
    H_DIM,
    S_DIM,
    S_MEAN,
    S_STD,
    STATE_KEYS,
    WorldModel,
    a2vec,
    save_checkpoint,
    vicreg,
)
from osler_jepa.actions import TREATMENT_EVENT_DIM, treatment_event_features
from osler_jepa.symbolic import direction_targets
from train_intervention_jepa import choose_device, collapse_metrics


SYNTHETIC_COLUMNS = (
    "synthetic_patient_id",
    "randomization_stratum",
    "arm",
    "horizon_h",
    "target",
    "baseline_value",
    "true_value",
    "observed_value",
    "observed_mask",
    "oracle_effect_vs_no_protocol",
    "act_insulin_iv_rate_u_hr",
    "act_fluids_rate_ml_hr",
    "act_kcl_rate_meq_hr",
    "synthetic_rct",
    "fictional_data",
    "not_real_patient_data",
    "causal_claim_allowed",
)

TARGET_TO_STATE = {
    "glucose": "G",
    "pH": "pH",
    "bicarbonate": "HCO3",
    "anion_gap": "anion_gap",
    "potassium": "Ke",
    "MAP": "MAP",
    "sodium": "Na",
    "creatinine": "creatinine",
    "urine_output": "urine_output",
}

STATE_TO_TARGET = {state: target for target, state in TARGET_TO_STATE.items()}
REPORT_TARGETS = tuple(TARGET_TO_STATE)
OMITTED_SYNTHETIC_TARGETS = ("heart_rate", "lactate")
ARM_ORDER = (
    "standard_protocol",
    "insulin_intensified",
    "insulin_conservative",
    "fluid_intensified",
    "potassium_repletion",
)


def _assert_synthetic_boundary(frame: pd.DataFrame) -> None:
    required = {
        "synthetic_rct": True,
        "fictional_data": True,
        "not_real_patient_data": True,
        "causal_claim_allowed": False,
    }
    for column, expected in required.items():
        if column not in frame.columns:
            raise ValueError(f"missing required synthetic boundary column: {column}")
        values = set(frame[column].dropna().unique().tolist())
        if values != {expected}:
            raise ValueError(
                f"unsafe synthetic boundary for {column}: expected only "
                f"{expected!r}, got {sorted(values)!r}"
            )


def _vectorized_k_store(ke, ph, creatinine, urine_output):
    shift = 0.60 * np.clip((7.40 - ph) / 0.10, -1.5, 3.0)
    acid_deficit = np.maximum(0.0, 7.35 - ph)
    ph_corrected_ke = ke - shift
    low_serum_penalty = 18.0 * np.maximum(0.0, 4.0 - ph_corrected_ke)
    urine_penalty = 0.04 * np.maximum(0.0, urine_output - 100.0)
    renal_retention = 4.0 * np.maximum(0.0, creatinine - 1.2)
    return np.clip(
        120.0 - 45.0 * acid_deficit - low_serum_penalty - urine_penalty
        + renal_retention,
        50.0,
        150.0,
    )


def _states_from_targets(frame: pd.DataFrame, prefix: str) -> np.ndarray:
    def col(target, default):
        name = f"{prefix}{target}"
        if name in frame:
            values = pd.to_numeric(frame[name], errors="coerce").to_numpy(float)
            return np.where(np.isfinite(values), values, default)
        return np.full(len(frame), default, dtype=float)

    glucose = col("glucose", 250.0)
    ph = col("pH", 7.2)
    bicarbonate = col("bicarbonate", 15.0)
    anion_gap = col("anion_gap", 18.0)
    potassium = col("potassium", 4.2)
    map_value = col("MAP", 80.0)
    sodium = col("sodium", 138.0)
    creatinine = col("creatinine", 1.2)
    urine_output = col("urine_output", 100.0)
    lactate = col("lactate", 2.0)

    volume = np.clip((map_value - 30.0) / 60.0 * 15.0, 5.0, 18.0)
    insulin_signal = np.full(len(frame), 1.0, dtype=float)
    osmolality = 2.0 * sodium + glucose / 18.0
    bhb = np.clip(np.maximum(0.0, anion_gap - 12.0) * 0.75, 0.0, 20.0)
    k_store = _vectorized_k_store(potassium, ph, creatinine, urine_output)
    osmotic_injury = np.zeros(len(frame), dtype=float)

    values = {
        "G": glucose,
        "pH": ph,
        "HCO3": bicarbonate,
        "anion_gap": anion_gap,
        "Ke": potassium,
        "MAP": map_value,
        "V": volume,
        "I": insulin_signal,
        "Na": sodium,
        "osmolality": osmolality,
        "creatinine": creatinine,
        "urine_output": urine_output,
        "BHB": bhb,
        "K_store": k_store,
        "osmotic_injury": osmotic_injury,
    }
    physical = np.column_stack([values[key] for key in STATE_KEYS]).astype(np.float32)
    return ((physical - S_MEAN) / S_STD).astype(np.float32)


def _pivot_synthetic(frame: pd.DataFrame, train_on: str) -> pd.DataFrame:
    if train_on not in {"truth", "observed"}:
        raise ValueError("train_on must be 'truth' or 'observed'")
    value_column = "true_value" if train_on == "truth" else "observed_value"
    index = ["synthetic_patient_id", "arm", "horizon_h"]

    future = (
        frame.pivot_table(
            index=index,
            columns="target",
            values=value_column,
            aggfunc="first",
        )
        .rename(columns={target: f"future_{target}" for target in REPORT_TARGETS})
        .reset_index()
    )
    baseline = (
        frame.drop_duplicates(["synthetic_patient_id", "arm", "target"])
        .pivot_table(
            index=["synthetic_patient_id", "arm"],
            columns="target",
            values="baseline_value",
            aggfunc="first",
        )
        .rename(columns={target: f"base_{target}" for target in REPORT_TARGETS})
        .reset_index()
    )
    oracle = (
        frame.pivot_table(
            index=index,
            columns="target",
            values="oracle_effect_vs_no_protocol",
            aggfunc="first",
        )
        .rename(columns={target: f"oracle_{target}" for target in REPORT_TARGETS})
        .reset_index()
    )
    actions = frame.drop_duplicates(["synthetic_patient_id", "arm"])[
        [
            "synthetic_patient_id",
            "arm",
            "randomization_stratum",
            "act_insulin_iv_rate_u_hr",
            "act_fluids_rate_ml_hr",
            "act_kcl_rate_meq_hr",
        ]
    ]
    table = future.merge(baseline, on=["synthetic_patient_id", "arm"], how="left")
    table = table.merge(oracle, on=index, how="left")
    table = table.merge(actions, on=["synthetic_patient_id", "arm"], how="left")
    return table.sort_values(["synthetic_patient_id", "horizon_h"]).reset_index(drop=True)


def load_synthetic_transitions(path: Path, train_on: str, max_patients: int | None,
                               seed: int) -> tuple[pd.DataFrame, dict]:
    frame = pd.read_parquet(path, columns=list(SYNTHETIC_COLUMNS))
    _assert_synthetic_boundary(frame)
    patients = np.asarray(sorted(frame["synthetic_patient_id"].unique()))
    if max_patients is not None and max_patients < len(patients):
        rng = np.random.default_rng(seed)
        keep = set(rng.choice(patients, size=max_patients, replace=False).tolist())
        frame = frame[frame["synthetic_patient_id"].isin(keep)].copy()
        patients = np.asarray(sorted(keep))
    table = _pivot_synthetic(frame, train_on=train_on)
    metadata = {
        "source": str(path),
        "train_on": train_on,
        "patients": int(len(patients)),
        "rows_long": int(len(frame)),
        "transitions": int(len(table)),
        "arms": sorted(frame["arm"].unique().tolist()),
        "horizons_h": sorted(int(x) for x in frame["horizon_h"].unique().tolist()),
        "targets": sorted(frame["target"].unique().tolist()),
        "modelled_targets": list(REPORT_TARGETS),
        "omitted_targets_not_in_dka_world_state": [
            target for target in OMITTED_SYNTHETIC_TARGETS
            if target in set(frame["target"].unique().tolist())
        ],
    }
    return table, metadata


def split_by_patient(table: pd.DataFrame, seed: int) -> dict[str, np.ndarray]:
    patients = table["synthetic_patient_id"].drop_duplicates().to_numpy()
    rng = np.random.default_rng(seed)
    rng.shuffle(patients)
    n_train = int(0.70 * len(patients))
    n_validation = int(0.15 * len(patients))
    groups = {
        "train": set(patients[:n_train]),
        "validation": set(patients[n_train:n_train + n_validation]),
        "test": set(patients[n_train + n_validation:]),
    }
    return {
        name: np.flatnonzero(table["synthetic_patient_id"].isin(values).to_numpy())
        for name, values in groups.items()
    }


def build_arrays(table: pd.DataFrame) -> dict[str, np.ndarray]:
    state = _states_from_targets(table, "base_")
    target = _states_from_targets(table, "future_")
    physical_action = np.zeros((len(table), A_DIM), dtype=np.float32)
    physical_action[:, 0] = pd.to_numeric(
        table["act_insulin_iv_rate_u_hr"], errors="coerce"
    ).fillna(0.0)
    physical_action[:, 4] = pd.to_numeric(
        table["act_fluids_rate_ml_hr"], errors="coerce"
    ).fillna(0.0)
    physical_action[:, 5] = pd.to_numeric(
        table["act_kcl_rate_meq_hr"], errors="coerce"
    ).fillna(0.0)
    action = np.asarray([a2vec(row) for row in physical_action], dtype=np.float32)
    event = treatment_event_features(physical_action)
    history = np.tile(
        np.concatenate([
            np.zeros(A_DIM, dtype=np.float32),
            np.ones(A_DIM, dtype=np.float32),
        ]),
        (len(table), 1),
    )
    delta = pd.to_numeric(table["horizon_h"], errors="coerce").to_numpy(np.float32)
    observed_mask = np.ones_like(state, dtype=np.float32)
    observed_age = np.zeros_like(state, dtype=np.float32)
    return {
        "state": state,
        "target": target,
        "action": action,
        "event": event.astype(np.float32),
        "history": history.astype(np.float32),
        "delta": delta,
        "observed_mask": observed_mask,
        "observed_age": observed_age,
    }


def _batch(arrays: dict[str, np.ndarray], indices: np.ndarray, device):
    return {
        key: torch.as_tensor(value[indices], dtype=torch.float32, device=device)
        for key, value in arrays.items()
    }


def train_epoch(model, arrays, indices, batch_size, optimizer, device, rng,
                direction_weight: float) -> dict:
    model.train()
    order = rng.permutation(indices)
    totals = []
    for start in range(0, len(order), batch_size):
        selected = order[start:start + batch_size]
        batch = _batch(arrays, selected, device)
        latent = model.encode_state(
            batch["state"],
            batch["history"],
            batch["observed_mask"],
            batch["observed_age"],
        )
        predicted_latent = model.predict_latent(
            latent,
            batch["action"],
            delta_hours=batch["delta"],
            treatment_events=batch["event"],
        )
        with torch.no_grad():
            target_latent = model.encode_target_state(batch["target"])
        predicted = model.D(predicted_latent)
        reconstructed = model.D(latent)
        one_step_state = F.mse_loss(predicted, batch["target"])
        one_step_latent = F.mse_loss(predicted_latent, target_latent)
        reconstruction = F.mse_loss(reconstructed, batch["state"])
        anti_collapse = vicreg(latent)
        outputs = model.symbolic_outputs(
            latent,
            batch["action"],
            delta_hours=batch["delta"],
            treatment_events=batch["event"],
        )
        direction_label = direction_targets(batch["target"] - batch["state"], S_STD)
        direction_loss = F.cross_entropy(
            outputs["direction_logits"].reshape(-1, 3),
            direction_label.reshape(-1),
        )
        loss = (
            one_step_state
            + 0.35 * one_step_latent
            + 0.15 * reconstruction
            + 0.08 * anti_collapse
            + direction_weight * direction_loss
        )
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.step()
        model.ema()
        totals.append({
            "loss": float(loss.detach()),
            "state_mse": float(one_step_state.detach()),
            "latent_mse": float(one_step_latent.detach()),
            "reconstruction": float(reconstruction.detach()),
            "anti_collapse": float(anti_collapse.detach()),
            "direction": float(direction_loss.detach()),
        })
    return {key: float(np.mean([row[key] for row in totals])) for key in totals[0]}


@torch.no_grad()
def predict(model, arrays, indices, batch_size, device, shuffle_actions=False):
    model.eval()
    predictions = []
    rng = np.random.default_rng(1901)
    for start in range(0, len(indices), batch_size):
        selected = indices[start:start + batch_size]
        batch = _batch(arrays, selected, device)
        action = batch["action"]
        event = batch["event"]
        if shuffle_actions:
            local = np.arange(len(selected))
            rng.shuffle(local)
            action = action[torch.as_tensor(local, dtype=torch.long, device=device)]
            event = event[torch.as_tensor(local, dtype=torch.long, device=device)]
        predicted, _, _ = model.predict_step(
            batch["state"],
            action,
            delta_hours=batch["delta"],
            history=batch["history"],
            observation_mask=batch["observed_mask"],
            observation_age=batch["observed_age"],
            treatment_events=event,
        )
        predictions.append(predicted.cpu().numpy())
    return np.concatenate(predictions, axis=0)


def physical(values: np.ndarray) -> np.ndarray:
    return values * S_STD + S_MEAN


def _target_index(target: str) -> int:
    return STATE_KEYS.index(TARGET_TO_STATE[target])


def _mae_by_target(table, prediction, target_norm, state_norm):
    pred = physical(prediction)
    target = physical(target_norm)
    state = physical(state_norm)
    report = {}
    for target_name in REPORT_TARGETS:
        index = _target_index(target_name)
        valid = np.isfinite(table[f"future_{target_name}"].to_numpy(float))
        if not valid.any():
            continue
        model_mae = float(np.mean(np.abs(pred[valid, index] - target[valid, index])))
        persistence_mae = float(np.mean(np.abs(state[valid, index] - target[valid, index])))
        report[target_name] = {
            "n": int(valid.sum()),
            "model_mae": round(model_mae, 5),
            "persistence_mae": round(persistence_mae, 5),
            "delta_vs_persistence": round(model_mae - persistence_mae, 5),
            "beats_persistence": bool(model_mae < persistence_mae),
        }
    return report


def _mae_by_horizon_target(table, prediction, target_norm, state_norm):
    report = {}
    for horizon in sorted(table["horizon_h"].unique().tolist()):
        mask = table["horizon_h"].to_numpy() == horizon
        report[str(int(horizon))] = _mae_by_target(
            table.loc[mask].reset_index(drop=True),
            prediction[mask],
            target_norm[mask],
            state_norm[mask],
        )
    return report


def _normalized_mse(prediction, target_norm):
    return float(np.mean((prediction - target_norm) ** 2))


def _effect_recovery(table: pd.DataFrame, prediction: np.ndarray, horizon=6) -> dict:
    pred = physical(prediction)
    selected = table["horizon_h"].to_numpy() == horizon
    frame = table.loc[selected].copy().reset_index(drop=True)
    if frame.empty:
        return {}
    pred = pred[selected]
    report = {}
    for target in REPORT_TARGETS:
        index = _target_index(target)
        standard = frame["arm"] == "standard_protocol"
        if not standard.any():
            continue
        standard_pred = float(np.mean(pred[standard.to_numpy(), index]))
        standard_true = float(frame.loc[standard, f"future_{target}"].mean())
        standard_oracle = float(frame.loc[standard, f"oracle_{target}"].mean())
        target_report = {}
        for arm in ARM_ORDER:
            if arm == "standard_protocol":
                continue
            mask = frame["arm"] == arm
            if not mask.any():
                continue
            predicted_difference = float(np.mean(pred[mask.to_numpy(), index]) - standard_pred)
            true_difference = float(frame.loc[mask, f"future_{target}"].mean() - standard_true)
            oracle_difference = float(frame.loc[mask, f"oracle_{target}"].mean() - standard_oracle)
            target_report[arm] = {
                "predicted_mean_difference_vs_standard": round(predicted_difference, 5),
                "true_mean_difference_vs_standard": round(true_difference, 5),
                "oracle_mean_difference_vs_standard": round(oracle_difference, 5),
                "predicted_vs_oracle_abs_error": round(abs(predicted_difference - oracle_difference), 5),
            }
        report[target] = target_report
    return report


def direction_accuracy(prediction, state_norm, target_norm):
    pred_label = direction_targets(
        torch.as_tensor(prediction - state_norm, dtype=torch.float32),
        S_STD,
    ).numpy()
    truth_label = direction_targets(
        torch.as_tensor(target_norm - state_norm, dtype=torch.float32),
        S_STD,
    ).numpy()
    changed = truth_label != 1
    return {
        "all": round(float((pred_label == truth_label).mean()), 5),
        "changed_only": round(float((pred_label[changed] == truth_label[changed]).mean()), 5)
        if changed.any() else None,
        "changed_comparisons": int(changed.sum()),
    }


def evaluate(model, table, arrays, indices, batch_size, device):
    heldout = table.iloc[indices].reset_index(drop=True)
    state = arrays["state"][indices]
    target = arrays["target"][indices]
    prediction = predict(model, arrays, indices, batch_size, device)
    shuffled = predict(model, arrays, indices, batch_size, device, shuffle_actions=True)
    per_target = _mae_by_target(heldout, prediction, target, state)
    horizon_target = _mae_by_horizon_target(heldout, prediction, target, state)
    factual_mse = _normalized_mse(prediction, target)
    shuffled_mse = _normalized_mse(shuffled, target)
    collapse = collapse_metrics(
        model,
        state[: min(len(state), 12000)],
        arrays["history"][indices][: min(len(state), 12000)],
        device,
    )
    return {
        "rows": int(len(indices)),
        "patients": int(heldout["synthetic_patient_id"].nunique()),
        "mae_by_target": per_target,
        "mae_by_horizon_target": horizon_target,
        "action_conditioning": {
            "factual_normalized_mse": round(factual_mse, 7),
            "shuffled_action_normalized_mse": round(shuffled_mse, 7),
            "shuffled_minus_factual": round(shuffled_mse - factual_mse, 7),
            "uses_interventions": bool(shuffled_mse > factual_mse),
        },
        "direction_accuracy": direction_accuracy(prediction, state, target),
        "known_effect_recovery_at_6h": _effect_recovery(heldout, prediction, horizon=6),
        "collapse": collapse,
    }


def train_model(args):
    started = time.time()
    device = choose_device(args.device)
    table, source_metadata = load_synthetic_transitions(
        Path(args.input), args.train_on, args.max_patients, args.seed
    )
    arrays = build_arrays(table)
    splits = split_by_patient(table, args.seed)
    model = WorldModel(dynamics_cell=args.dynamics_cell).to(device)
    optimizer = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=args.learning_rate,
        weight_decay=1e-5,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=max(args.epochs, 1)
    )
    rng = np.random.default_rng(args.seed + 991)
    best_validation = math.inf
    best_state = None
    history = []
    print(
        f"device: {device}; synthetic patients={source_metadata['patients']}; "
        f"transitions={source_metadata['transitions']}; train_on={args.train_on}"
    )
    print(
        f"split: train={len(splits['train'])}, "
        f"validation={len(splits['validation'])}, test={len(splits['test'])}"
    )
    for epoch in range(1, args.epochs + 1):
        row = train_epoch(
            model,
            arrays,
            splits["train"],
            args.batch_size,
            optimizer,
            device,
            rng,
            args.direction_weight,
        )
        scheduler.step()
        validation = evaluate(
            model,
            table,
            arrays,
            splits["validation"],
            args.eval_batch_size,
            device,
        )
        val_mse = validation["action_conditioning"]["factual_normalized_mse"]
        row["validation_normalized_mse"] = val_mse
        row["epoch"] = epoch
        history.append(row)
        if val_mse < best_validation:
            best_validation = val_mse
            best_state = {
                name: value.detach().cpu().clone()
                for name, value in model.state_dict().items()
            }
        print(
            f"epoch {epoch:03d}/{args.epochs} loss={row['loss']:.5f} "
            f"state={row['state_mse']:.5f} val_mse={val_mse:.6f} "
            f"direction={row['direction']:.4f}"
        )
    if best_state is not None:
        model.load_state_dict(best_state)
    model.eval()
    test = evaluate(model, table, arrays, splits["test"], args.eval_batch_size, device)
    report = {
        "model": "Synthetic-RCT-trained DKA WorldModel candidate",
        "trained_at_unix": int(time.time()),
        "device": str(device),
        "source": source_metadata,
        "training": {
            "epochs": args.epochs,
            "batch_size": args.batch_size,
            "learning_rate": args.learning_rate,
            "direction_weight": args.direction_weight,
            "best_validation_normalized_mse": best_validation,
            "history": history,
        },
        "split_by_patient": {
            name: int(table.iloc[index]["synthetic_patient_id"].nunique())
            for name, index in splits.items()
        },
        "architecture": {
            "world_model": "dka_world_model.WorldModel",
            "dynamics_cell": args.dynamics_cell,
            "state_dim": S_DIM,
            "action_dim": A_DIM,
            "latent_dim": 48,
            "trained_on_oracle_truth": args.train_on == "truth",
        },
        "test": test,
        "boundary": {
            "synthetic_rct": True,
            "fictional_data": True,
            "not_real_patient_data": True,
            "causal_claim_allowed": False,
            "clinical_use_allowed": False,
            "checkpoint_promotion_allowed": False,
            "interpretation": (
                "This report measures recovery of simulator truth, not human "
                "clinical treatment effects."
            ),
        },
        "training_seconds": round(time.time() - started, 2),
    }
    save_checkpoint(model, args.checkpoint, metadata=report)
    Path(args.report).write_text(json.dumps(report, indent=2), encoding="utf-8")
    print("\n=== synthetic RCT held-out report ===")
    print(json.dumps({
        "patients": report["source"]["patients"],
        "test_rows": report["test"]["rows"],
        "best_validation_normalized_mse": best_validation,
        "action_conditioning": report["test"]["action_conditioning"],
        "direction_accuracy": report["test"]["direction_accuracy"],
        "collapse": report["test"]["collapse"],
        "checkpoint_promotion_allowed": False,
    }, indent=2))
    print(f"saved checkpoint: {args.checkpoint}")
    print(f"saved report:     {args.report}")
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default="/private/tmp/osler_synthetic_rct_dka_100k.parquet")
    parser.add_argument("--checkpoint", default="/private/tmp/osler_synthetic_rct_jepa_candidate.pt")
    parser.add_argument("--report", default="/private/tmp/osler_synthetic_rct_jepa_candidate_report.json")
    parser.add_argument("--train-on", choices=("truth", "observed"), default="truth")
    parser.add_argument("--max-patients", type=int)
    parser.add_argument("--epochs", type=int, default=8)
    parser.add_argument("--batch-size", type=int, default=4096)
    parser.add_argument("--eval-batch-size", type=int, default=8192)
    parser.add_argument("--learning-rate", type=float, default=8e-4)
    parser.add_argument("--direction-weight", type=float, default=0.05)
    parser.add_argument("--seed", type=int, default=20260711)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--dynamics-cell", choices=("residual_mlp", "ltc"), default="residual_mlp")
    args = parser.parse_args()
    train_model(args)


if __name__ == "__main__":
    main()
